name: dralfadhli_lawapp
description: تطبيق مكتب المحاماة د. الفضلي لعرض القضايا والتقارير.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.22.0
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.15.4
  firebase_storage: ^11.6.5
  file_picker: ^5.2.3
  url_launcher: ^6.1.10
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png

  fonts:
    - family: Cairo
